package org.firstinspires.ftc.teamcode.commands;

public enum State {
    IDLE, TRANSFER, GROUND_INTAKING, SUB_INTAKING, SUB_GRABBING, HIGH_BUCKET, HIGH_BUCKET_SLAM, LOW_BUCKET, HIGH_BAR, HIGH_BAR_SLAM, LOW_BAR, LOW_BAR_SLAM
}
